name: 'dbt_transform'
version: '1.0.0'
config-version: 2
profile: 'dbt_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: ">=1.8.0"

packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

models:
  dbt_transform:
    +materialized: table
    +location: us-central1