# Chemin: docker-compose.yml
version: '3.8'

services:
  opportunity-manager:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./data_sources:/app/data_sources
      - ./exports:/app/exports:rw  # Ajout du droit d'écriture explicite
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge