name: API Pipeline

on:
  push:
    paths:
      - 'api/opportunity-manager/**'
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PROJECT_ID: e-datacap
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/e-datacap/opportunity-manager
  SERVICE_ACCOUNT: terraform-sa@e-datacap.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      
      - name: Build and Push
        working-directory: ./api/opportunity-manager
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/app:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}/app:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy opportunity-manager \
            --image ${{ env.GAR_LOCATION }}/app:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --allow-unauthenticated