name: Infrastructure Pipeline

on:
  push:
    paths:
      - 'infra/**'
    branches: [ main, develop ]
  workflow_dispatch:

env:
  PROJECT_ID: e-datacap
  REGION: us-central1
  SERVICE_ACCOUNT: terraform-sa@e-datacap.iam.gserviceaccount.com
  TF_STATE_BUCKET: edata-terraform-tfstate-files

permissions:
  contents: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Clean Terraform Lock
        run: gsutil rm -f gs://${{ env.TF_STATE_BUCKET }}/terraform/tfstate/default.tflock || true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="prefix=terraform/tfstate"

      - name: Terraform Format
        run: |
          terraform fmt -recursive
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "style: auto-format terraform files" && \
           git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }})
      
      - name: Terraform Plan
        run: |
          terraform plan \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var-file="env/dev.tfvars" \
            -out=tfplan
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
